<?php

namespace App\Filament\App\Widgets;

use App\Models\App;
use Filament\Actions\BulkActionGroup;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;
use Filament\Widgets\TableWidget;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class AppStats extends TableWidget
{

    protected function getViewData(): array
    {
        return parent::getViewData(); // TODO: Change the autogenerated stub
    }

    public function getTableRecords(): \Illuminate\Support\Collection
    {
        $apps = App::query()->select('name')
            ->distinct()
            ->pluck('name');

        return collect($apps->map(function($name) {

            $app = App::query()
                ->where('name', $name)
                ->first();

            return [
                'key' => $app->name,
                'name' => $app->name,
                'count_installs' => App::query()
                    ->where('name', $app->name)
                    ->where('status', '!=', App::STATE_CREATED)
                    ->count(),
                'count_active' => App::query()
                    ->where('name', $app->name)
                    ->where('status', App::STATE_ACTIVE)
                    ->count(),
                'count_transactions' => $this->getTransactionCounts($app),
            ];
        }));
    }

    public function getTransactionCounts(App $app): int
    {
        return $app->resource_name::getTransactions();
    }

    public function getTableRecordKey($record): string
    {
        // Возвращаем уникальное поле из вашего массива
        return (string) $record['key'];
    }

    public function table(Table $table): Table
    {
        return $table
            ->records(fn () => $this->getTableRecords())
            ->columns([
                TextColumn::make('name')->label('Название'),
                TextColumn::make('count_installs')->label('Установлено'),
                TextColumn::make('count_active')->label('Активно'),
                TextColumn::make('count_transactions')->label('Транзакций'),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                //
            ])
            ->recordActions([
                //
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    //
                ]),
            ]);
    }
}
