<?php

namespace App\Filament\Resources\Core\UserResource\Pages;

use App\Filament\Resources\Core\UserResource;
use App\Helpers\Traits\SyncAmoCRMPage;
use Filament\Forms\Components\TextInput;
use Filament\Resources\Pages\EditRecord;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;
use Illuminate\Support\Facades\Hash;

class EditUser extends EditRecord
{
    use SyncAmoCRMPage;

    protected static string $resource = UserResource::class;

    //    protected static ?string $navigationLabel = 'Профиль';

    public function form(Schema $schema): Schema
    {
        return $schema
            ->schema([
                Section::make('Основная информация')
                    ->schema([
                        TextInput::make('email')
                            ->label('Почта')
                            ->email()
                            ->required()
                            ->maxLength(255)
                            ->unique(ignoreRecord: true),
                        TextInput::make('name')
                            ->label('Имя')
                            ->required()
                            ->maxLength(255),
                        TextInput::make('uuid')
                            ->label('Идентификатор')
                            ->disabled()
                            ->visible(fn (): bool => (bool) auth()->user()?->is_root),
                        TextInput::make('new_password')
                            ->label('Новый пароль')
                            ->password()
                            ->revealable()
                            ->minLength(8),
                    ])->columnSpan([
                        'sm' => 2,
                    ]),
            ])->columns([
                'sm' => 3,
                'lg' => null,
            ]);
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        if (! empty($data['new_password'])) {

            $this->record->password = Hash::make($data['new_password']);
            $this->record->save();
        }

        unset($data['new_password']);

        return $data;
    }

    protected function getHeaderWidgets(): array
    {
        return [];
    }

    public function getHeaderWidgetsColumns(): int|array
    {
        return 3; // TODO: Change the autogenerated stub
    }
}
