<?php

namespace App\Filament\Resources\Core\UserResource\Pages;

use App\Filament\Resources\Core\UserResource;
use App\Models\amoCRM\Staff;
use App\Models\amoCRM\Status;
use App\Models\User;
use App\Services\amoCRM\Client;
use App\Services\amoCRM\Models\Account;
use Filament\Schemas\Components\Section;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\EditRecord;
use App\Helpers\Traits\SyncAmoCRMPage;
use Filament\Schemas\Schema;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\URL;

class EditUser extends EditRecord
{
    use SyncAmoCRMPage;

    protected static string $resource = UserResource::class;

//    protected static ?string $navigationLabel = 'Профиль';

    public function form(Schema $schema): Schema
    {
        return $schema
            ->schema([
                Section::make('Основная информация')
                    ->schema([
                        TextInput::make('email')
                            ->label('Почта'),
                        TextInput::make('name')
                            ->label('Логин'),
                        TextInput::make('uuid')
                            ->label('Идентификатор')
                            ->disabled(),
                        TextInput::make('new_password')
                            ->label('Новый пароль'),
                    ])->columnSpan([
                        'sm' => 2,
                    ]),
            ])->columns([
                'sm' => 3,
                'lg' => null,
            ]);
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        if (!empty($data['new_password'])) {

            $this->record->password = Hash::make($data['new_password']);
            $this->record->save();
        }

        return $data;
    }

    protected function getHeaderWidgets(): array
    {
        return [];
    }

    public function getHeaderWidgetsColumns(): int|array
    {
        return 3; // TODO: Change the autogenerated stub
    }
}
