<?php

namespace App\Filament\Resources\Core\UserResource\Pages;

use App\Filament\Resources\Core\UserResource;
use App\Services\amoCRM\Client;
use App\Services\amoCRM\Models\Account;
use Filament\Infolists\Components\Section;
use Filament\Infolists\Infolist;
use Filament\Notifications\Notification;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ViewRecord;
use Filament\Support\Colors\Color;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Request;

class ViewUser extends ViewRecord
{
    protected static string $resource = UserResource::class;

    protected static ?string $title = 'Аккаунт';

    protected function getActions(): array
    {
        return [
            Actions\Action::make('amocrmAuth')
                ->action('amocrmAuth')
                ->color(fn() => $this->record->account->active ? Color::Green : Color::Red)
                ->label(fn() => $this->record->account->active ? 'amoCRM Подключена' : 'Подключить amoCRM')
                ->disabled(fn() => $this->record->account->active),

            Actions\Action::make('activeUpdate')
                ->action('amocrmUpdate')
                ->label('Синхронизировать')
                ->disabled(fn() => !$this->record->account->active)
        ];
    }

    public function mount(int|string $record): void
    {
        if (Auth::id() !== (int)$record) {

            $this->redirect(UserResource::getUrl('view', ['record' => Auth::id()]));
        }

        parent::mount($record);

        $auth = Request::get('auth');

        if ($auth === '0')
            Notification::make()
                ->title('amoCRM не подключена. Подключите или обратитесь в чат поддержки')
                ->warning()
                ->send();

        if ($auth === '1')
            Notification::make()
                ->title('amoCRM успешно подключена')
                ->success()
                ->send();
    }

    protected function getHeaderWidgets(): array
    {
        return [];
    }

    public function getHeaderWidgetsColumns(): int|array
    {
        return 3; // TODO: Change the autogenerated stub
    }

    public function amocrmAuth(): void
    {
        $account = Auth::user()->account;

        if (!$account->active) {

            Redirect::to('https://www.amocrm.ru/oauth/?state='.Auth::user()->uuid.'&mode=popup&client_id='.config('services.amocrm.client_id'));

        } else
            Notification::make()
                ->title('amoCRM уже подключена')
                ->warning()
                ->send();
    }

    /**
     * @throws \Exception
     */
    public function amocrmUpdate(): void
    {
        $amoApi = (new Client(Auth::user()->account))->init();

        if ($amoApi->auth) {

            Account::users($amoApi);
            Account::statuses($amoApi);
            Account::fields($amoApi);

            Notification::make()
                ->title('Успешно обновлено')
                ->success()
                ->send();
        }
    }

    protected function authorizeAccess(): void
    {
        if (!Auth::user()->is_root && Auth::id() !== $this->record->id) {

            $this->redirect(UserResource::getUrl('view', ['record' => Auth::id()]));
        }
    }
}
