<?php

namespace App\Filament\Resources\Integrations\DocResource\Pages;

use App\Filament\Resources\Integrations\DocResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class EditDoc extends EditRecord
{
    protected static string $resource = DocResource::class;

    protected function getHeaderActions(): array
    {
        return [];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        for($i = 0; $i < count($data); $i++) {

            unset($data[$i]['link']);
        }

        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        if ($data['settings']) {
            $data['settings'] = json_decode($data['settings'], true);

            for($i = 0; count($data['settings']) !== $i; $i++) {

                $data['settings'][$i]['link'] = \route('doc.hook', [
                    'user' => Auth::user()->uuid,
                    'doc'  => $i,
                ]);

//                $body = json_decode($data['bodies'], true)[$i] ?? [];

//                $data['settings'][$i]['body'] = json_encode($body, JSON_UNESCAPED_UNICODE);
            }
        }

        return $data;
    }

    public function getRelationManagers(): array
    {
        return [
            DocResource\RelationManagers\AmocrmFieldsRelationManager::class,
        ];
    }
}
