<?php

namespace App\Filament\App\Pages;

use App\Filament\App\Widgets\AlfaPreview;
use App\Filament\App\Widgets\BizonPreview;
use App\Filament\App\Widgets\GetCoursePreview;
use App\Livewire\Widgets\Preview;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Infolists\Components\TextEntry;
use Filament\Infolists\Concerns\InteractsWithInfolists;
use Filament\Infolists\Contracts\HasInfolists;
use Filament\Infolists\Infolist;
use Filament\Pages\Page;
use Illuminate\Support\Facades\Auth;

class Market extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.app.pages.market';

    protected static ?string $title = 'Магазин интеграций';

    protected function getHeaderWidgets(): array
    {
        foreach (Auth::user()->apps as $app)
        {
            $widgets[] = Preview::make( ['app' => $app]);
        }

        return $widgets ?? [];
    }

    public function getFooterWidgetsColumns(): int|string|array
    {
        return 3; // TODO: Change the autogenerated stub
    }

    public function getHeaderWidgetsColumns(): int | array
    {
        return 3;
    }
}
